### ISSUE TITLE
Can't instantiate `SM`: undefined `points`

### ISSUE THREAD

**Issue by midrare** [slaypni/SM-15#8]
Trying to instantiate an `SM` produces a type error. For some reason, `points` is undefined.

```shell
C:\Users\shodan\Desktop>coffee --version
CoffeeScript version 2.7.0

C:\Users\shodan\Desktop>coffee supermemo.coffee
(a)add, (n)next, (N)next advanceably, (s)save, (l)load, (e)exit
TypeError: Cannot read properties of undefined (reading 'length')
    at exponentialRegression (C:\Users\shodan\Desktop\supermemo.coffee:314:14)
    at ForgettingCurve.uf (C:\Users\shodan\Desktop\supermemo.coffee:252:18)
    at RFM.rf (C:\Users\shodan\Desktop\supermemo.coffee:261:61)
    at OFM.<anonymous> (C:\Users\shodan\Desktop\supermemo.coffee:277:68)
    at OFM.<anonymous> (C:\Users\shodan\Desktop\supermemo.coffee:542:16)
    at OFM.update (C:\Users\shodan\Desktop\supermemo.coffee:277:12)
    at new OFM (C:\Users\shodan\Desktop\supermemo.coffee:272:6)
    at new SM (C:\Users\shodan\Desktop\supermemo.coffee:16:12)
    at main (C:\Users\shodan\Desktop\supermemo.coffee:443:8)
    at Object.<anonymous> (C:\Users\shodan\Desktop\supermemo.coffee:540:1)
    at Object.<anonymous> (C:\Users\shodan\Desktop\supermemo.coffee:5:4)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Object.CoffeeScript.run (C:\Users\shodan\AppData\Roaming\npm\node_modules\coffeescript\lib\coffeescript\index.js:67:23)
    at compileScript (C:\Users\shodan\AppData\Roaming\npm\node_modules\coffeescript\lib\coffeescript\command.js:285:29)
    at compilePath (C:\Users\shodan\AppData\Roaming\npm\node_modules\coffeescript\lib\coffeescript\command.js:237:14)
    at Object.exports.run (C:\Users\shodan\AppData\Roaming\npm\node_modules\coffeescript\lib\coffeescript\command.js:158:20)
    at Object.<anonymous> (C:\Users\shodan\AppData\Roaming\npm\node_modules\coffeescript\bin\coffee:22:45)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Function.Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by midrare** [comment]
Nevermind, it's the script is for Coffeescript v1.
